#!/bin/bash

while read line; do
    name=$(basename $line)
    status=$(git_status $line)
    if [ $status -eq 2 ]; then
        color="#b03a2e"
    elif [ $status -eq 1 ]; then
        color="#ca6f1e"
    else
        color="#1e8449"
    fi
    echo "<span color='$color'> ⚫ <b>$name</b> </span>"
done < ~/Git/GitStatus/git_folders.txt
